---
- name: Create user using loops
  hosts: all
  become: true
  tasks:
    
    - name: create the users
      user: 
        name: "{{item}}"
        state: present

      with_items:
        - yar
        - war
        - rar
