---
- name: Creating the users using var
  hosts: all
  become: true
  
  vars:
    user: ravi
    user1: raj

  tasks:
    - name: create the users {{ user }}
      user:
        name: "{{ user }}"
        state: present
